version: '3'

services:
  alumni-backend:
    build:
      context: ../AlumniPBackendIO
    image: alumni-backend:latest
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development

    restart: always